# docker-compose.yml
version: "3"
services:
    server:
        build: ./server
        depends_on:
            - postgres
        working_dir: /usr/src/app
        environment:
            DATABASE_URL: postgres://admin:admin@postgres:5432/db
            NODE_ENV: production
            PORT: 3000
        ports:
            - "3000:3000"
        command: sh -c "npm install && npm run dev"
        volumes:
            - ./server:/usr/src/app/

    postgres:
        image: postgres:10.4
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: db
        volumes:
            - ./server/db/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

    client:
        build:
            context: ./client
            target: production
        ports:
            - "8081:80"
